db.zen.insertMany([
    {
        "user" : "Gopi",
        "codekata" : 235,
        "attendance" : "Present",
        "topics" : "React",
        "topic_date" : new Date("<2020-10-05>"),
        "task_date" : new Date("<2020-10-10>"),
        "tasks" : "movie_app",
        "company_drives" : "HCL",
        "company_drives_date" : new Date("<2020-10-20>"),
        "placement": "Appeared",
        "mentors" : "Sathish"
    },
    {
        "user" : "shankar",
        "codekata" : 200,
        "attendance" : "Present",
        "topics" : "MongoDB",
        "topic_date" : new Date("<2020-10-15>"),
        "task_date" : new Date("<2020-10-16>"),
        "tasks" : "mongo_commands",
        "company_drives" : "TCS",
        "company_drives_date" : new Date("<2020-10-25>"),
        "placement": "Appeared",
        "mentors" : "Sathish"
    },    
    {
        "user" : "anas",
        "codekata" : 175,
        "attendance" : "Present",
        "topics" : "Node_js",
        "topic_date" : new Date("<2020-10-20>"),
        "task_date" : new Date("<2020-10-21>"),
        "tasks" : "create_api",
        "company_drives" : "ZOHO",
        "company_drives_date" : new Date("<2020-10-28>"),
        "placement": "Appeared",
        "mentors" : "Sathish"
    },
    {
        "user" : "Shan",
        "codekata" : 150,
        "attendance" : "Present",
        "topics" : "HTML",
        "topic_date" : new Date("<2020-10-07>"),
        "task_date" : new Date("<2020-10-09>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "WIPRO",
        "company_drives_date" : new Date("<2020-10-22>"),
        "placement": "Appeared",
        "mentors" : "Magesh"
    },    
    {
        "user" : "sanjay",
        "codekata" : 250,
        "attendance" : "Present",
        "topics" : "CSS",
        "topic_date" : new Date("<2020-10-12>"),
        "task_date" : new Date("<2020-10-14>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "ZOHO",
        "company_drives_date" : new Date("<2020-10-28>"),
        "placement": "Appeared",
        "mentors" : "Magesh"
    }, 
    {
        "user" : "ram",
        "codekata" : 93,
        "attendance" : "Absent",
        "topics" : "JavaScript",
        "topic_date" : new Date("<2020-10-19>"),
        "task_date" : new Date("<2020-10-23>"),
        "tasks" : "functions",
        "company_drives" : "Cognizant",
        "company_drives_date" : new Date("<2020-10-31>"),
        "placement": "Not_appeared",
        "mentors" : "Rupan"
    },    
    {
        "user" : "swamy",
        "codekata" : 180,
        "attendance" : "Present",
        "topics" : "React",
        "topic_date" : new Date("<2020-10-05>"),
        "task_date" : new Date("<2020-10-16>"),
        "tasks" : "movie_app",
        "company_drives" : "HCL",
        "company_drives_date" : new Date("<2020-10-20>"),
        "placement": "Appeared",
        "mentors" : "Raghav"
    },
    {
        "user" : "ramar",
        "codekata" : 125,
        "attendance" : "Present",
        "topics" : "CSS",
        "topic_date" : new Date("<2020-10-12>"),
        "task_date" : new Date("<2020-10-20>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "TCS",
        "company_drives_date" : new Date("<2020-10-25>"),
        "placement": "Appeared",
        "mentors" : "Magesh"
    },    
    {
        "user" : "lakshman",
        "codekata" : 155,
        "attendance" : "Present",
        "topics" : "Node_js",
        "topic_date" : new Date("<2020-10-20>"),
        "task_date" : new Date("<2020-10-21>"),
        "tasks" : "create_api",
        "company_drives" : "ZOHO",
        "company_drives_date" : new Date("<2020-10-28>"),
        "placement": "Appeared",
        "mentors" : "Raghav"
    },
    {
        "user" : "seetha",
        "codekata" : 55,
        "attendance" : "Present",
        "topics" : "MongoDB",
        "topic_date" : new Date("<2020-10-15>"),
        "task_date" : new Date("<2020-10-19>"),
        "tasks" : "mongo_commands",
        "company_drives" : "HCL",
        "company_drives_date" : new Date("<2020-10-20>"),
        "placement": "Appeared",
        "mentors" : "Raghav"
    },    
    {
        "user" : "paartha",
        "codekata" : 68,
        "attendance" : "Present",
        "topics" : "React",
        "topic_date" : new Date("<2020-10-05>"),
        "task_date" : new Date("<2020-10-16>"),
        "tasks" : "movie_app",
        "company_drives" : "ZOHO",
        "company_drives_date" : new Date("<2020-10-28>"),
        "placement": "Not_appeared",
        "mentors" : "Raghav"
    }, 
    {
        "user" : "Harini",
        "codekata" : 250,
        "attendance" : "Absent",
        "topics" : "JavaScript",
        "topic_date" : new Date("<2020-10-19>"),
        "task_date" : new Date("<2020-10-23>"),
        "tasks" : "functions",
        "company_drives" : "Cognizant",
        "company_drives_date" : new Date("<2020-10-31>"),
        "placement": "Appeared",
        "mentors" : "Rupan"
    },    {
        "user" : "hari",
        "codekata" : 95,
        "attendance" : "Present",
        "topics" : "HTML",
        "topic_date" : new Date("<2020-10-07>"),
        "task_date" : new Date("<2020-10-09>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "HCL",
        "company_drives_date" : new Date("<2020-10-20>"),
        "placement": "Not_appeared",
        "mentors" : "Magesh"
    },
    {
        "user" : "Samantha",
        "codekata" : 200,
        "attendance" : "Present",
        "topics" : "Node_js",
        "topic_date" : new Date("<2020-10-20>"),
        "task_date" : new Date("<2020-10-25>"),
        "tasks" : "create_api",
        "company_drives" : "WIPRO",
        "company_drives_date" : new Date("<2020-10-22>"),
        "placement": "Appeared",
        "mentors" : "Raghav"
    },    
    {
        "user" : "trisha",
        "codekata" : 88,
        "attendance" : "Present",
        "topics" : "React",
        "topic_date" : new Date("<2020-10-05>"),
        "task_date" : new Date("<2020-10-15>"),
        "tasks" : "movie_app",
        "company_drives" : "WIPRO",
        "company_drives_date" : new Date("<2020-10-22>"),
        "placement": "Not_appeared",
        "mentors" : "Raghav"
    },
    {
        "user" : "nayan",
        "codekata" : 189,
        "attendance" : "Present",
        "topics" : "JavaScript",
        "topic_date" : new Date("<2020-10-19>"),
        "task_date" : new Date("<2020-10-25>"),
        "tasks" : "functions",
        "company_drives" : "Cognizant",
        "company_drives_date" : new Date("<2020-10-31>"),
        "placement": "Appeared",
        "mentors" : "Rupan"
    },
    {
        "user" : "sk",
        "codekata" : 159,
        "attendance" : "Absent",
        "topics" : "MongoDB",
        "topic_date" : new Date("<2020-10-15>"),
        "task_date" : new Date("<2020-10-21>"),
        "tasks" : "mongo_commands",
        "company_drives" : "TCS",
        "company_drives_date" : new Date("<2020-10-25>"),
        "placement": "Appeared",
        "mentors" : "Raghav"
    },
    {
        "user" : "sivakumar",
        "codekata" : 175,
        "attendance" : "Present",
        "topics" : "MongoDB",
        "topic_date" : new Date("<2020-10-15>"),
        "task_date" : new Date("<2020-10-20>"),
        "tasks" : "mongo_commands",
        "company_drives" : "Cognizant",
        "company_drives_date" : new Date("<2020-10-31>"),
        "placement": "Appeared",
        "mentors" : "Raghav"
    },
    {
        "user" : "surya",
        "codekata" : 105,
        "attendance" : "Absent",
        "topics" : "React",
        "topic_date" : new Date("<2020-10-05>"),
        "task_date" : new Date("<2020-10-22>"),
        "tasks" : "movie_app",
        "company_drives" : "HCL",
        "company_drives_date" : new Date("<2020-10-20>"),
        "placement": "Appeared",
        "mentors" : "Raghav"
    },    
    {
        "user" : "karthi",
        "codekata" : 265,
        "attendance" : "Present",
        "topics" : "HTML",
        "topic_date" : new Date("<2020-10-07>"),
        "task_date" : new Date("<2020-10-11>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "WIPRO",
        "company_drives_date" : new Date("<2020-10-22>"),
        "placement": "Appeared",
        "mentors" : "Magesh"
    }, 
    {
        "user" : "VK",
        "codekata" : 300,
        "attendance" : "Present",
        "topics" : "JavaScript",
        "topic_date" : new Date("<2020-10-19>"),
        "task_date" : new Date("<2020-10-29>"),
        "tasks" : "functions",
        "company_drives" : "Cognizant",
        "company_drives_date" : new Date("<2020-10-31>"),
        "placement": "Appeared",
        "mentors" : "Rupan"
    },    {
        "user" : "Prabhu",
        "codekata" : 30,
        "attendance" : "Absent",
        "topics" : "CSS",
        "topic_date" : new Date("<2020-10-12>"),
        "task_date" : new Date("<2020-10-16>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "HCL",
        "company_drives_date" : new Date("<2020-10-20>"),
        "placement": "Appeared",
        "mentors" : "Magesh"
    },
    {
        "user" : "premji",
        "codekata" : 177,
        "attendance" : "Present",
        "topics" : "MongoDB",
        "topic_date" : new Date("<2020-10-15>"),
        "task_date" : new Date("<2020-10-17>"),
        "tasks" : "mongo_commands",
        "company_drives" : "TCS",
        "company_drives_date" : new Date("<2020-10-25>"),
        "placement": "Not_appeared",
        "mentors" : "Raghav"
    },    
    {
        "user" : "yuvan",
        "codekata" : 133,
        "attendance" : "Present",
        "topics" : "React",
        "topic_date" : new Date("<2020-10-05>"),
        "task_date" : new Date("<2020-10-11>"),
        "tasks" : "movie_app",
        "company_drives" : "ZOHO",
        "company_drives_date" : new Date("<2020-10-28>"),
        "placement": "Appeared",
        "mentors" : "Raghav"
    },
    {
        "user" : "rajen",
        "codekata" : 222,
        "attendance" : "Absent",
        "topics" : "Node_js",
        "topic_date" : new Date("<2020-10-20>"),
        "task_date" : new Date("<2020-10-22>"),
        "tasks" : "create_api",
        "company_drives" : "WIPRO",
        "company_drives_date" : new Date("<2020-10-22>"),
        "placement": "Appeared",
        "mentors" : "Raghav"
    },    
    {
        "user" : "kural",
        "codekata" : 50,
        "attendance" : "Absent",
        "topics" : "HTML",
        "topic_date" : new Date("<2020-10-07>"),
        "task_date" : new Date("<2020-10-09>"),
        "tasks" : "responsive_web_design",
        "company_drives" : "Cognizant",
        "company_drives_date" : new Date("<2020-10-31>"),
        "placement": "Appeared",
        "mentors" : "Magesh"
    }, 
    {
        "user" : "simbu",
        "codekata" : 350,
        "attendance" : "Present",
        "topics" : "Node_js",
        "topic_date" : new Date("<2020-10-20>"),
        "task_date" : new Date("<2020-10-25>"),
        "tasks" : "create_api",
        "company_drives" : "ZOHO",
        "company_drives_date" : new Date("<2020-10-28>"),
        "placement": "Appeared",
        "mentors" : "Raghav"
    }
    
]);